# Generated by Django 6.0.4 on 2026-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=15)),
                ('price', models.IntegerField(verbose_name=20)),
            ],
        ),
    ]
