# Generated by Django 6.0.4 on 2026-04-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='course',
            field=models.ImageField(blank=True, null=True, upload_to='Books/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(max_length=15),
        ),
    ]
