# Generated by Django 6.0.4 on 2026-04-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0002_books_course_alter_books_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='course',
            new_name='photo',
        ),
    ]
